Repository Team-TagCafe/TagCafe-BE, pull requests merged in 2025-04, with the labels that each got.

#21 [deploy/#18 -> main] 배포 셋업 & 완료
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/Minjin/TagCafe/config/KakaoAuthController.java
  src/main/java/com/Minjin/TagCafe/config/WebConfig.java
  src/main/java/com/Minjin/TagCafe/controller/CafeController.java
  src/main/java/com/Minjin/TagCafe/controller/FAQController.java
  src/main/java/com/Minjin/TagCafe/controller/HomeController.java
  src/main/java/com/Minjin/TagCafe/controller/UserController.java
Labels: Deploy

#26 [fix] #25 - 회원 로직 및 배포 프로세스 픽스
  .github/workflows/deploy.yml
  src/main/java/com/Minjin/TagCafe/config/KakaoAuthController.java
  src/main/java/com/Minjin/TagCafe/controller/UserController.java
Labels: Fix

#28 Feat/#27 s3
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/Minjin/TagCafe/config/S3Config.java
  src/main/java/com/Minjin/TagCafe/controller/CafeController.java
  src/main/java/com/Minjin/TagCafe/controller/ReportedCafeController.java
  src/main/java/com/Minjin/TagCafe/dto/CafeDto.java
  src/main/java/com/Minjin/TagCafe/dto/CafeHomeDTO.java
  src/main/java/com/Minjin/TagCafe/dto/CafeSearchDTO.java
  src/main/java/com/Minjin/TagCafe/dto/ReviewDTO.java
  src/main/java/com/Minjin/TagCafe/dto/SavedCafeDTO.java
  src/main/java/com/Minjin/TagCafe/entity/CafeImage.java
  src/main/java/com/Minjin/TagCafe/service/CafeService.java
Labels: Feat
